[workspace]
members = [
    "bytes",
    "communication",
    "kafkaesque",
    "logging",
    "sort",
    "state",
    "timely",
]

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = true
debug-assertions = false
